Eigen::CSCMatrix Struct Reference
Eigen::CSCMatrix Struct Reference
Helper class to convert Eigen::Matrix to csc struct expected by OSQP.
#include <eigen-osqp/CSCMatrix.h>
Public Member Functions
CSCMatrix ()
Default constructor. Allocate memory for an empty matrix.
void updateTriangularDefault (const MatrixConstRef &mat)
Update current csc matrix to a new one. Only the upper triangular part is considered.
void updateDefault (const MatrixConstRef &mat)
Update current csc matrix to a new one.
void updateAndAddIdentity (const MatrixConstRef &mat)
Update current csc matrix to a new one and add an identity matrix beneath it.
void updateTriangularDefault (const MatrixCompressSparseConstRef &mat)
Update current csc matrix to a new one. Only the upper triangular part is considered.
void updateDefault (const MatrixCompressSparseConstRef &mat)
Update current csc matrix to a new one.
void updateAndAddIdentity (const MatrixCompressSparseConstRef &mat)
Update current csc matrix to a new one and add an identity matrix beneath it.
csc * matrix () noexcept
Get the csc matrix pointer.
MatrixDense toDenseEigen () const
Convert csc matrix to Eigen dense matrix.
MatrixSparse toSparseEigen () const
Convert csc matrix to Eigen sparse matrix.
Detailed Description
Helper class to convert Eigen::Matrix to csc struct expected by OSQP.
Constructor & Destructor Documentation
CSCMatrix()
Eigen::CSCMatrix::CSCMatrix ()
Default constructor. Allocate memory for an empty matrix.
Member Function Documentation
matrix()
csc* Eigen::CSCMatrix::matrix () inline noexcept
Get the csc matrix pointer.
Referenced by Eigen::OSQP::solve().
toDenseEigen()
MatrixDense Eigen::CSCMatrix::toDenseEigen () const
Convert csc matrix to Eigen dense matrix.
toSparseEigen()
MatrixSparse Eigen::CSCMatrix::toSparseEigen () const
Convert csc matrix to Eigen sparse matrix.
updateAndAddIdentity() [1/2]
void Eigen::CSCMatrix::updateAndAddIdentity (const MatrixConstRef & mat)
Update current csc matrix to a new one and add an identity matrix beneath it.
Parameters
mat Dense matrix to convert.
Referenced by Eigen::OSQP::solve().
updateAndAddIdentity() [2/2]
void Eigen::CSCMatrix::updateAndAddIdentity (const MatrixCompressSparseConstRef & mat)
Update current csc matrix to a new one and add an identity matrix beneath it.
Parameters
mat Compress sparse matrix to convert.
updateDefault() [1/2]
void Eigen::CSCMatrix::updateDefault (const MatrixConstRef & mat)
Update current csc matrix to a new one.
Parameters
mat Dense matrix to convert.
Referenced by Eigen::OSQP::solve().
updateDefault() [2/2]
void Eigen::CSCMatrix::updateDefault (const MatrixCompressSparseConstRef & mat)
Update current csc matrix to a new one.
Parameters
mat Compress sparse matrix to convert.
updateTriangularDefault() [1/2]
void Eigen::CSCMatrix::updateTriangularDefault (const MatrixConstRef & mat)
Update current csc matrix to a new one. Only the upper triangular part is considered.
Note
It is up to the user to check that the matrix is symmetrical.
Parameters
mat Dense matrix to convert.
Referenced by Eigen::OSQP::solve().
updateTriangularDefault() [2/2]
void Eigen::CSCMatrix::updateTriangularDefault (const MatrixCompressSparseConstRef & mat)
Update current csc matrix to a new one. Only the upper triangular part is considered.
Note
It is up to the user to check that the matrix is symmetrical.
Parameters
mat Dense matrix to convert.