Eigen::OSQP Class Reference
Eigen::OSQP Class Reference
Eigen wrapper class of osqp. The class wraps the c-library osqp for Eigen matrix. It accepts both dense and sparse matrix. To compute a QP, just set the number of variables and solve.
#include <eigen-osqp/OSQP.h>
Public Member Functions
OSQP ()
Default constructor.
~OSQP () noexcept=default
Default destructor.
void admmStepRho (c_float rho) noexcept
ADMM step rho. Default is 0.1.
c_float admmStepRho () const noexcept
void admmStepSigma (c_float sigma) noexcept
ADMM step sigma. Default is 1e-6.
c_float admmStepSigma () const noexcept
void scalingIter (c_int scaling) noexcept
Heuristic data scaling iterations. If 0, scaling disabled. Default is 10.
c_int scalingIter () const noexcept
void maxIter (c_int maxIter) noexcept
Maximum number of iteration. Default is 4000.
c_int maxIter () const noexcept
void absConvergenceTol (c_float tol) noexcept
Absolute convergence tolerance. Default is 1e-3.
c_float absConvergenceTol () const noexcept
void relConvergenceTol (c_float tol) noexcept
Relative convergence tolerance. Default is 1e-3.
c_float relConvergenceTol () const noexcept
void primalInfeasibilityTol (c_float tol) noexcept
Primal infeasibility tolerance. Default is 1e-4.
c_float primalInfeasibilityTol () const noexcept
void dualInfeasibilityTol (c_float tol) noexcept
Dual infeasibility tolerance. Default is 1e-4.
c_float dualInfeasibilityTol () const noexcept
void relaxationParam (c_float alpha) noexcept
Relaxation parameter. Default is 1.6.
c_float relaxationParam () const noexcept
void linearSystemSolver (linsys_solver_type solver) noexcept
Linear solver. Default is QDLDL_SOLVER.
linsys_solver_type linearSystemSolver () const noexcept
void scaleTermination (bool doScaleTermination) noexcept
Use scale termination criteria. Default is false.
bool scaleTermination () const noexcept
void checkTermination (c_int checkValue) noexcept
check termination interval. If 0, termination checking is disabled. Default is 25.
c_int checkTermination () const noexcept
void warmStart (bool ws) noexcept
Warm start. Default is true.
bool warmStart () const noexcept
void polish (bool doPolish) noexcept
Polish ADMM solution.
bool polish () const noexcept
void polishDelta (c_float delta) noexcept
Regularization parameter for polish.
c_float polishDelta () const noexcept
void polishRefineIter (c_int iter) noexcept
Iterative refinement steps in polish.
c_int polishRefineIter () const noexcept
void verbose (bool doPrint) noexcept
Write osqp progress.
bool verbose () const noexcept
void problem (int nrVar, int nrConstr)
Set up the problem parameters.
const VectorDense & result () const noexcept
Return the qp result.
template<typename TQ , typename TA >
bool solve (const TQ &Q, const VectorConstRef &c, const TA &A, const VectorConstRef &AL, const VectorConstRef &AU, const VectorConstRef &XL, const VectorConstRef &XU)
Solve the given problem. The function problem(int, int) needs to be called before calling this function.
template<typename TQ , typename TA >
bool solve (const TQ &Q, const VectorConstRef &c, const TA &A, const VectorConstRef &AL, const VectorConstRef &AU)
Solve the given problem. The function problem(int, int) needs to be called before calling this function.
template<typename TQ >
bool solve (const TQ &Q, const VectorConstRef &c)
Solve unconstrained problem. The function problem(int, int) needs to be called before calling this function.
c_int iter () const noexcept
Get number of iterations taken.
void inform (std::ostream &os) const noexcept
Print solver status.
c_int status () const noexcept
Get solver status.
c_float costResult () const noexcept
Get cost result.
c_float primalResidualNorm () const noexcept
Get norm of primal residual.
c_float dualResidualNorm () const noexcept
Get norm of dual residual.
Detailed Description
Eigen wrapper class of osqp. The class wraps the c-library osqp for Eigen matrix. It accepts both dense and sparse matrix. To compute a QP, just set the number of variables and solve.
Note
Dense matrix are converted to an osqp sparse representation. All zeros in it won't be deleted away.
Constructor & Destructor Documentation
OSQP()
Eigen::OSQP::OSQP ()
Default constructor.
~OSQP()
Eigen::OSQP::~OSQP () default noexcept
Default destructor.
Member Function Documentation
absConvergenceTol() [1/2]
void Eigen::OSQP::absConvergenceTol (c_float tol) inline noexcept
Absolute convergence tolerance. Default is 1e-3.
absConvergenceTol() [2/2]
c_float Eigen::OSQP::absConvergenceTol () const inline noexcept
admmStepRho() [1/2]
void Eigen::OSQP::admmStepRho (c_float rho) inline noexcept
ADMM step rho. Default is 0.1.
admmStepRho() [2/2]
c_float Eigen::OSQP::admmStepRho () const inline noexcept
admmStepSigma() [1/2]
void Eigen::OSQP::admmStepSigma (c_float sigma) inline noexcept
ADMM step sigma. Default is 1e-6.
admmStepSigma() [2/2]
c_float Eigen::OSQP::admmStepSigma () const inline noexcept
checkTermination() [1/2]
void Eigen::OSQP::checkTermination (c_int checkValue) inline noexcept
check termination interval. If 0, termination checking is disabled. Default is 25.
checkTermination() [2/2]
c_int Eigen::OSQP::checkTermination () const inline noexcept
costResult()
c_float Eigen::OSQP::costResult () const inline noexcept
Get cost result.
dualInfeasibilityTol() [1/2]
void Eigen::OSQP::dualInfeasibilityTol (c_float tol) inline noexcept
Dual infeasibility tolerance. Default is 1e-4.
dualInfeasibilityTol() [2/2]
c_float Eigen::OSQP::dualInfeasibilityTol () const inline noexcept
dualResidualNorm()
c_float Eigen::OSQP::dualResidualNorm () const inline noexcept
Get norm of dual residual.
inform()
void Eigen::OSQP::inform (std::ostream & os) const inline noexcept
Print solver status.
iter()
c_int Eigen::OSQP::iter () const inline noexcept
Get number of iterations taken.
linearSystemSolver() [1/2]
void Eigen::OSQP::linearSystemSolver (linsys_solver_type solver) inline noexcept
Linear solver. Default is QDLDL_SOLVER.
linearSystemSolver() [2/2]
linsys_solver_type Eigen::OSQP::linearSystemSolver () const inline noexcept
maxIter() [1/2]
void Eigen::OSQP::maxIter (c_int maxIter) inline noexcept
Maximum number of iteration. Default is 4000.
References maxIter().
Referenced by maxIter().
maxIter() [2/2]
c_int Eigen::OSQP::maxIter () const inline noexcept
polish() [1/2]
void Eigen::OSQP::polish (bool doPolish) inline noexcept
Polish ADMM solution.
polish() [2/2]
bool Eigen::OSQP::polish () const inline noexcept
polishDelta() [1/2]
void Eigen::OSQP::polishDelta (c_float delta) inline noexcept
Regularization parameter for polish.
polishDelta() [2/2]
c_float Eigen::OSQP::polishDelta () const inline noexcept
polishRefineIter() [1/2]
void Eigen::OSQP::polishRefineIter (c_int iter) inline noexcept
Iterative refinement steps in polish.
polishRefineIter() [2/2]
c_int Eigen::OSQP::polishRefineIter () const inline noexcept
primalInfeasibilityTol() [1/2]
void Eigen::OSQP::primalInfeasibilityTol (c_float tol) inline noexcept
Primal infeasibility tolerance. Default is 1e-4.
primalInfeasibilityTol() [2/2]
c_float Eigen::OSQP::primalInfeasibilityTol () const inline noexcept
primalResidualNorm()
c_float Eigen::OSQP::primalResidualNorm () const inline noexcept
Get norm of primal residual.
problem()
void Eigen::OSQP::problem (int nrVar, int nrConstr)
Set up the problem parameters.
Parameters
nrVar Number of variable
nrConstr Number of constraints
relaxationParam() [1/2]
void Eigen::OSQP::relaxationParam (c_float alpha) inline noexcept
Relaxation parameter. Default is 1.6.
relaxationParam() [2/2]
c_float Eigen::OSQP::relaxationParam () const inline noexcept
relConvergenceTol() [1/2]
void Eigen::OSQP::relConvergenceTol (c_float tol) inline noexcept
Relative convergence tolerance. Default is 1e-3.
relConvergenceTol() [2/2]
c_float Eigen::OSQP::relConvergenceTol () const inline noexcept
result()
const VectorDense& Eigen::OSQP::result () const inline noexcept
Return the qp result.
Returns
Result (uninitialize vector if the qp fails)
scaleTermination() [1/2]
void Eigen::OSQP::scaleTermination (bool doScaleTermination) inline noexcept
Use scale termination criteria. Default is false.
scaleTermination() [2/2]
bool Eigen::OSQP::scaleTermination () const inline noexcept
scalingIter() [1/2]
void Eigen::OSQP::scalingIter (c_int scaling) inline noexcept
Heuristic data scaling iterations. If 0, scaling disabled. Default is 10.
scalingIter() [2/2]
c_int Eigen::OSQP::scalingIter () const inline noexcept
solve() [1/3]
template<typename TQ , typename TA > bool Eigen::OSQP::solve (const TQ & Q, const VectorConstRef & c, const TA & A, const VectorConstRef & AL, const VectorConstRef & AU, const VectorConstRef & XL, const VectorConstRef & XU)
Solve the given problem. The function problem(int, int) needs to be called before calling this function.
Template Parameters
TQ Matrix type. Either a dense or compressed sparse matrix (or a reference to it).
TA Matrix type. Either a dense or compressed sparse matrix (or a reference to it).
Parameters
Q Quadratic part of the cost.
c Linear part of the cost.
A Constraint matrix.
AL Lower bound of the constraints.
AU Upper bound of the constraints.
XL Lower bound of the variables.
XU Upper bound of the variables.
References Eigen::CSCMatrix::matrix(), Eigen::CSCMatrix::updateAndAddIdentity(), and Eigen::CSCMatrix::updateTriangularDefault().
solve() [2/3]
template<typename TQ , typename TA > bool Eigen::OSQP::solve (const TQ & Q, const VectorConstRef & c, const TA & A, const VectorConstRef & AL, const VectorConstRef & AU)
Solve the given problem. The function problem(int, int) needs to be called before calling this function.
Template Parameters
TQ Matrix type. Either a dense or compressed sparse matrix (or a reference to it).
TA Matrix type. Either a dense or compressed sparse matrix (or a reference to it).
Parameters
Q Quadratic part of the cost.
c Linear part of the cost.
A Constraint matrix.
AL Lower bound of the constraints.
AU Upper bound of the constraints.
References Eigen::CSCMatrix::matrix(), Eigen::CSCMatrix::updateDefault(), and Eigen::CSCMatrix::updateTriangularDefault().
solve() [3/3]
template<typename TQ > bool Eigen::OSQP::solve (const TQ & Q, const VectorConstRef & c)
Solve unconstrained problem. The function problem(int, int) needs to be called before calling this function.
Template Parameters
TQ Matrix type. Either a dense or compressed sparse matrix (or a reference to it).
Parameters
Q Quadratic part of the cost.
c Linear part of the cost.
References Eigen::CSCMatrix::matrix(), and Eigen::CSCMatrix::updateTriangularDefault().
status()
c_int Eigen::OSQP::status () const inline noexcept
Get solver status.
verbose() [1/2]
void Eigen::OSQP::verbose (bool doPrint) inline noexcept
Write osqp progress.
verbose() [2/2]
bool Eigen::OSQP::verbose () const inline noexcept
warmStart() [1/2]
void Eigen::OSQP::warmStart (bool ws) inline noexcept
Warm start. Default is true.
warmStart() [2/2]
bool Eigen::OSQP::warmStart () const inline noexcept